// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: n5zmr3PovmtS4tuUW5NRYW
// Component: nFtVKAyz2Z7m

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import NavBar from "../../NavBar"; // plasmic-import: PU1QtwXYhxPS/component
import Button from "../../Button"; // plasmic-import: HO-X_0IZqCJj/component
import ProductCard from "../../ProductCard"; // plasmic-import: xuP2bIhMMXP2/component
import Rating from "../../Rating"; // plasmic-import: iqH6qZlzizN8/component
import EmojiValueProps from "../../EmojiValueProps"; // plasmic-import: hG8jx9k8w2OW/component
import Value from "../../Value"; // plasmic-import: UctlctSR9cQF/component
import Footer from "../../Footer"; // plasmic-import: B2XQrBD_TUYH/component

import { useScreenVariants as useScreenVariantspo83RxkSPvq } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: PO83RXK-sPvq/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: n5zmr3PovmtS4tuUW5NRYW/projectcss
import sty from "./PlasmicHomepage.module.css"; // plasmic-import: nFtVKAyz2Z7m/css

import MenuIcon from "./icons/PlasmicIcon__Menu"; // plasmic-import: aeKwmROxlPAB/icon
import RightArrowIcon from "./icons/PlasmicIcon__RightArrow"; // plasmic-import: KYheckxim0Dt/icon
import PlaneIcon from "./icons/PlasmicIcon__Plane"; // plasmic-import: yfGl4AZuPARw/icon
import DocumentIcon from "./icons/PlasmicIcon__Document"; // plasmic-import: 8BQNvI3FVRZQ/icon
import LockIcon from "./icons/PlasmicIcon__Lock"; // plasmic-import: 8SOd6d1CWBVE/icon
import SpeakerphoneIcon from "./icons/PlasmicIcon__Speakerphone"; // plasmic-import: ej68R9jPwIN9/icon
import MedalIcon from "./icons/PlasmicIcon__Medal"; // plasmic-import: s2rid2F1yZHQ/icon
import LeafIcon from "./icons/PlasmicIcon__Leaf"; // plasmic-import: HFt1NiIPrTdw/icon
import ShoeIcon from "./icons/PlasmicIcon__Shoe"; // plasmic-import: cQyF0xjECpBq/icon
import PeaceIcon from "./icons/PlasmicIcon__Peace"; // plasmic-import: DQJuT14WpUch/icon

createPlasmicElementProxy;

export type PlasmicHomepage__VariantMembers = {};
export type PlasmicHomepage__VariantsArgs = {};
type VariantPropType = keyof PlasmicHomepage__VariantsArgs;
export const PlasmicHomepage__VariantProps = new Array<VariantPropType>();

export type PlasmicHomepage__ArgsType = {
  container42?: React.ReactNode;
};
type ArgPropType = keyof PlasmicHomepage__ArgsType;
export const PlasmicHomepage__ArgProps = new Array<ArgPropType>("container42");

export type PlasmicHomepage__OverridesType = {
  root?: Flex__<"div">;
  navBar?: Flex__<typeof NavBar>;
  container3?: Flex__<"div">;
  h1?: Flex__<"h1">;
  container4?: Flex__<"div">;
  container?: Flex__<"div">;
  emojiValueProps?: Flex__<typeof EmojiValueProps>;
  columns?: Flex__<"div">;
  container42?: Flex__<"div">;
  container5?: Flex__<"div">;
  container6?: Flex__<"div">;
  container434?: Flex__<"div">;
  container433?: Flex__<"div">;
  footer?: Flex__<typeof Footer>;
};

export interface DefaultHomepageProps {}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicHomepage__RenderFunc(props: {
  variants: PlasmicHomepage__VariantsArgs;
  args: PlasmicHomepage__ArgsType;
  overrides: PlasmicHomepage__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const currentUser = useCurrentUser?.() || {};

  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantspo83RxkSPvq()
  });

  return (
    <React.Fragment>
      <Head>
        <meta name="twitter:card" content="summary" />
        <title key="title">{PlasmicHomepage.pageMetadata.title}</title>
        <meta
          key="og:title"
          property="og:title"
          content={PlasmicHomepage.pageMetadata.title}
        />
        <meta
          key="twitter:title"
          name="twitter:title"
          content={PlasmicHomepage.pageMetadata.title}
        />
        <meta
          key="description"
          name="description"
          content={PlasmicHomepage.pageMetadata.description}
        />
        <meta
          key="og:description"
          property="og:description"
          content={PlasmicHomepage.pageMetadata.description}
        />
        <meta
          key="twitter:description"
          name="twitter:description"
          content={PlasmicHomepage.pageMetadata.description}
        />
      </Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            sty.root
          )}
        >
          <NavBar
            data-plasmic-name={"navBar"}
            data-plasmic-override={overrides.navBar}
            className={classNames("__wab_instance", sty.navBar)}
          />

          <section className={classNames(projectcss.all, sty.section__typK)}>
            <Stack__
              as={"div"}
              data-plasmic-name={"container3"}
              data-plasmic-override={overrides.container3}
              hasGap={true}
              className={classNames(projectcss.all, sty.container3)}
            >
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__qbprW)}
              >
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__ttNtm)}
                >
                  <h1
                    data-plasmic-name={"h1"}
                    data-plasmic-override={overrides.h1}
                    className={classNames(
                      projectcss.all,
                      projectcss.h1,
                      projectcss.__wab_text,
                      sty.h1
                    )}
                  >
                    {"Welcome my store, there are many shoes !!"}
                  </h1>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__mFe1E
                    )}
                  >
                    {
                      "A nam quisque orci ut vestibulum eget sem aliquet a dictumst condimentum ad quam porta a inceptos consectetur sagittis a a commodo ridiculus tempor egestas."
                    }
                  </div>
                </Stack__>
                <Button
                  className={classNames("__wab_instance", sty.button__iD5X)}
                  colors={"black"}
                  endIcon={
                    <RightArrowIcon
                      className={classNames(projectcss.all, sty.svg__thqe3)}
                      role={"img"}
                    />
                  }
                  rounded={true}
                  showEndIcon={true}
                  size={"large"}
                  submitsForm={true}
                >
                  {"Shop"}
                </Button>
              </Stack__>
            </Stack__>
          </section>
          <section className={classNames(projectcss.all, sty.section__qIiXe)}>
            <div
              data-plasmic-name={"container4"}
              data-plasmic-override={overrides.container4}
              className={classNames(projectcss.all, sty.container4)}
            >
              <div className={classNames(projectcss.all, sty.freeBox__yrsM9)}>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__gxktA
                  )}
                >
                  {"Featured"}
                </div>
                <Button
                  className={classNames("__wab_instance", sty.button__xyQsP)}
                  colors={"link"}
                  endIcon={
                    <RightArrowIcon
                      className={classNames(projectcss.all, sty.svg__fs0GF)}
                      role={"img"}
                    />
                  }
                  showEndIcon={true}
                  submitsForm={true}
                >
                  {"See more"}
                </Button>
              </div>
            </div>
            <Stack__
              as={"div"}
              data-plasmic-name={"container"}
              data-plasmic-override={overrides.container}
              hasGap={true}
              className={classNames(projectcss.all, sty.container)}
            >
              <ProductCard
                className={classNames(
                  "__wab_instance",
                  sty.productCard___5F42B
                )}
                img={{
                  src: "/plasmic/copy_of_t_22/images/airforce107Png.webp",
                  fullWidth: 936,
                  fullHeight: 1170,
                  aspectRatio: undefined
                }}
                rating={
                  <Rating
                    className={classNames("__wab_instance", sty.rating___3GUtt)}
                    rating={"four"}
                  />
                }
                tags={
                  <Button
                    colors={"lightGray"}
                    size={"small"}
                    submitsForm={true}
                  >
                    {"New"}
                  </Button>
                }
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__fIlHo
                  )}
                >
                  {"ADIDAS ULTRABOOST DNA X LEGO\u00ae PLATES SHOES"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__kBa75
                  )}
                >
                  {"If you can dream it, you can build it."}
                </div>
              </ProductCard>
              <ProductCard
                className={classNames("__wab_instance", sty.productCard__vtw0H)}
                dollars={"79"}
                img={{
                  src: "/plasmic/copy_of_t_22/images/imagespng.jpg",
                  fullWidth: 201,
                  fullHeight: 251,
                  aspectRatio: undefined
                }}
                rating={
                  <Rating
                    className={classNames("__wab_instance", sty.rating__xb7Gg)}
                    rating={"threeHalf"}
                  />
                }
                tags={
                  <Button
                    colors={"lightGray"}
                    size={"small"}
                    submitsForm={true}
                  >
                    {"New"}
                  </Button>
                }
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__hle66
                  )}
                >
                  {"Nike Air Zoom Pegasus 38"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__bIbet
                  )}
                >
                  {"If you can dream it, you can build it."}
                </div>
              </ProductCard>
              <ProductCard
                className={classNames("__wab_instance", sty.productCard__q0Ixr)}
                dollars={"64"}
                img={{
                  src: "/plasmic/copy_of_t_22/images/airforce1071Png.webp",
                  fullWidth: 936,
                  fullHeight: 1170,
                  aspectRatio: undefined
                }}
                rating={
                  <Rating
                    className={classNames("__wab_instance", sty.rating__rybdg)}
                    rating={"two"}
                  />
                }
                tags={
                  <Button
                    colors={"lightGray"}
                    size={"small"}
                    submitsForm={true}
                  >
                    {"New"}
                  </Button>
                }
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__cXxv9
                  )}
                >
                  {"Club C 85 Vintage Men's Shoes"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__yHgkw
                  )}
                >
                  {"If you can dream it, you can build it."}
                </div>
              </ProductCard>
              <ProductCard
                className={classNames("__wab_instance", sty.productCard__xx1W)}
                dollars={"99"}
                img={{
                  src: "/plasmic/copy_of_t_22/images/imagespng.jpg",
                  fullWidth: 201,
                  fullHeight: 251,
                  aspectRatio: undefined
                }}
                rating={
                  <Rating
                    className={classNames("__wab_instance", sty.rating__z8Ls)}
                    rating={"four"}
                  />
                }
                tags={
                  <Button
                    colors={"lightGray"}
                    size={"small"}
                    submitsForm={true}
                  >
                    {"New"}
                  </Button>
                }
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__diwEp
                  )}
                >
                  {"Nike Air Max Genome"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__a9Wi
                  )}
                >
                  {"If you can dream it, you can build it."}
                </div>
              </ProductCard>
              <ProductCard
                className={classNames("__wab_instance", sty.productCard__rp77B)}
                dollars={"79"}
                img={{
                  src: "/plasmic/copy_of_t_22/images/airforce1071Png.webp",
                  fullWidth: 936,
                  fullHeight: 1170,
                  aspectRatio: undefined
                }}
                rating={
                  <Rating
                    className={classNames("__wab_instance", sty.rating__erUiG)}
                    rating={"five"}
                  />
                }
                tags={
                  <Button
                    colors={"lightGray"}
                    size={"small"}
                    submitsForm={true}
                  >
                    {"New"}
                  </Button>
                }
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___1JAjx
                  )}
                >
                  {"ULTRABOOST DNA 1.0 SHOES"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__aPsHf
                  )}
                >
                  {"If you can dream it, you can build it."}
                </div>
              </ProductCard>
              <ProductCard
                cents={"50"}
                className={classNames("__wab_instance", sty.productCard__wp1Gj)}
                dollars={"65"}
                img={{
                  src: "/plasmic/copy_of_t_22/images/nikeAirForce107WhiteButterflyPrintCustompng.jpg",
                  fullWidth: 500,
                  fullHeight: 500,
                  aspectRatio: undefined
                }}
                rating={
                  <Rating
                    className={classNames("__wab_instance", sty.rating___5IIhq)}
                    rating={"threeHalf"}
                  />
                }
                tags={
                  <Button
                    colors={"lightGray"}
                    size={"small"}
                    submitsForm={true}
                  >
                    {"New"}
                  </Button>
                }
              />
            </Stack__>
          </section>
          <section className={classNames(projectcss.all, sty.section__hmS6R)}>
            <Stack__
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox__ocqGz)}
            >
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__t0YyU)}
              >
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__dTx9P)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__mwbzN
                    )}
                  >
                    {"Our best shoe sale of the year"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__e6GY
                    )}
                  >
                    {
                      "Signature style. Unsurpassed quality and comfort. Now\u2019s the perfect time to save on iconic shoes."
                    }
                  </div>
                </Stack__>
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__gr5Wr)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___9FSb
                    )}
                  >
                    <React.Fragment>
                      <React.Fragment>{"3 "}</React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ fontStyle: "italic" }}
                      >
                        {"for"}
                      </span>
                      <React.Fragment>{" $169"}</React.Fragment>
                    </React.Fragment>
                  </div>
                  <Button
                    colors={"black"}
                    endIcon={
                      <RightArrowIcon
                        className={classNames(projectcss.all, sty.svg__lpgQl)}
                        role={"img"}
                      />
                    }
                    rounded={true}
                    showEndIcon={true}
                    size={"large"}
                    submitsForm={true}
                  >
                    {"Shop sale"}
                  </Button>
                </Stack__>
              </Stack__>
            </Stack__>
          </section>
          <EmojiValueProps
            data-plasmic-name={"emojiValueProps"}
            data-plasmic-override={overrides.emojiValueProps}
            className={classNames("__wab_instance", sty.emojiValueProps)}
          >
            <Stack__
              as={"div"}
              data-plasmic-name={"columns"}
              data-plasmic-override={overrides.columns}
              hasGap={true}
              className={classNames(projectcss.all, sty.columns)}
            >
              <div className={classNames(projectcss.all, sty.column__oKMxR)}>
                <Value
                  children2={
                    <Button
                      className={classNames(
                        "__wab_instance",
                        sty.button__ga5Vi
                      )}
                      colors={"black"}
                      endIcon={
                        <RightArrowIcon
                          className={classNames(projectcss.all, sty.svg__rBEqV)}
                          role={"img"}
                        />
                      }
                      rounded={true}
                      size={"large"}
                      submitsForm={true}
                    >
                      {"Read our letter"}
                    </Button>
                  }
                  className={classNames("__wab_instance", sty.value__k23BU)}
                  icon={
                    <PlaneIcon
                      className={classNames(projectcss.all, sty.svg__jNpg6)}
                      role={"img"}
                    />
                  }
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___5VRwl
                    )}
                  >
                    {"Worldwide shipping"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__p2SXx
                    )}
                  >
                    {"Special financing and earn rewards."}
                  </div>
                </Value>
              </div>
              <div className={classNames(projectcss.all, sty.column__w6Or8)}>
                <Value
                  children2={
                    <Button
                      className={classNames(
                        "__wab_instance",
                        sty.button__bmjDp
                      )}
                      colors={"black"}
                      endIcon={
                        <RightArrowIcon
                          className={classNames(
                            projectcss.all,
                            sty.svg___7BLvL
                          )}
                          role={"img"}
                        />
                      }
                      rounded={true}
                      size={"large"}
                      submitsForm={true}
                    >
                      {"Read our letter"}
                    </Button>
                  }
                  className={classNames("__wab_instance", sty.value___7CwWi)}
                  icon={
                    <DocumentIcon
                      className={classNames(projectcss.all, sty.svg__njUXs)}
                      role={"img"}
                    />
                  }
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___2UdH
                    )}
                  >
                    {"30-day guarantee"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__ypNuF
                    )}
                  >
                    {"Free return policy."}
                  </div>
                </Value>
              </div>
              <div className={classNames(projectcss.all, sty.column__benxv)}>
                <Value
                  children2={
                    <Button
                      className={classNames(
                        "__wab_instance",
                        sty.button__w50Il
                      )}
                      colors={"black"}
                      endIcon={
                        <RightArrowIcon
                          className={classNames(projectcss.all, sty.svg__cN86)}
                          role={"img"}
                        />
                      }
                      rounded={true}
                      size={"large"}
                      submitsForm={true}
                    >
                      {"Read our letter"}
                    </Button>
                  }
                  className={classNames("__wab_instance", sty.value__lOjOj)}
                  icon={
                    <LockIcon
                      className={classNames(projectcss.all, sty.svg__zhyGf)}
                      role={"img"}
                    />
                  }
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__teP5
                    )}
                  >
                    {"Secured payments"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__ofyWw
                    )}
                  >
                    {"We accept major credit cards."}
                  </div>
                </Value>
              </div>
            </Stack__>
          </EmojiValueProps>
          <section className={classNames(projectcss.all, sty.section___7N3WO)}>
            <div
              data-plasmic-name={"container42"}
              data-plasmic-override={overrides.container42}
              className={classNames(projectcss.all, sty.container42)}
            >
              {renderPlasmicSlot({
                defaultContents: (
                  <div
                    className={classNames(projectcss.all, sty.freeBox__iSaU7)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__q1A0I
                      )}
                    >
                      {"Just added"}
                    </div>
                    <Button
                      className={classNames(
                        "__wab_instance",
                        sty.button__bwqFd
                      )}
                      colors={"link"}
                      endIcon={
                        <RightArrowIcon
                          className={classNames(projectcss.all, sty.svg__jTgFg)}
                          role={"img"}
                        />
                      }
                      showEndIcon={true}
                      submitsForm={true}
                    >
                      {"See more"}
                    </Button>
                  </div>
                ),
                value: args.container42
              })}
            </div>
            <div
              data-plasmic-name={"container5"}
              data-plasmic-override={overrides.container5}
              className={classNames(projectcss.all, sty.container5)}
            >
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__tIgOq)}
              >
                <ProductCard
                  img={{
                    src: "/plasmic/copy_of_t_22/images/shoe14.png",
                    fullWidth: 840,
                    fullHeight: 840,
                    aspectRatio: undefined
                  }}
                  tags={
                    <Button
                      colors={"lightGray"}
                      size={"small"}
                      submitsForm={true}
                    >
                      {"New"}
                    </Button>
                  }
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__ooJpY
                    )}
                  >
                    {"ADIDAS ULTRABOOST DNA X LEGO\u00ae PLATES SHOES"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___98EhQ
                    )}
                  >
                    {"If you can dream it, you can build it."}
                  </div>
                </ProductCard>
                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__xClu
                  )}
                  img={{
                    src: "/plasmic/copy_of_t_22/images/shoe15.png",
                    fullWidth: 864,
                    fullHeight: 1080,
                    aspectRatio: undefined
                  }}
                  tags={
                    <Button
                      colors={"lightGray"}
                      size={"small"}
                      submitsForm={true}
                    >
                      {"New"}
                    </Button>
                  }
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__zzFj
                    )}
                  >
                    {"Nike Air Zoom Pegasus 38"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__tHmoh
                    )}
                  >
                    {"If you can dream it, you can build it."}
                  </div>
                </ProductCard>
                <ProductCard
                  className={classNames("__wab_instance", sty.productCard__pfy)}
                  img={{
                    src: "/plasmic/copy_of_t_22/images/shoe16.png",
                    fullWidth: 840,
                    fullHeight: 840,
                    aspectRatio: undefined
                  }}
                  tags={
                    <Button
                      colors={"lightGray"}
                      size={"small"}
                      submitsForm={true}
                    >
                      {"New"}
                    </Button>
                  }
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__nYKnO
                    )}
                  >
                    {"Club C 85 Vintage Men's Shoes"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___0ERx
                    )}
                  >
                    {"If you can dream it, you can build it."}
                  </div>
                </ProductCard>
                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__seCY
                  )}
                  img={{
                    src: "/plasmic/copy_of_t_22/images/shoe17.png",
                    fullWidth: 864,
                    fullHeight: 1080,
                    aspectRatio: undefined
                  }}
                  tags={
                    <Button
                      colors={"lightGray"}
                      size={"small"}
                      submitsForm={true}
                    >
                      {"New"}
                    </Button>
                  }
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__bcigM
                    )}
                  >
                    {"Nike Air Max Genome"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__xz70V
                    )}
                  >
                    {"If you can dream it, you can build it."}
                  </div>
                </ProductCard>
                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__ivyWp
                  )}
                  img={{
                    src: "/plasmic/copy_of_t_22/images/shoe18.png",
                    fullWidth: 840,
                    fullHeight: 840,
                    aspectRatio: undefined
                  }}
                  tags={
                    <Button
                      colors={"lightGray"}
                      size={"small"}
                      submitsForm={true}
                    >
                      {"New"}
                    </Button>
                  }
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__uQwpp
                    )}
                  >
                    {"ULTRABOOST DNA 1.0 SHOES"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___29UsX
                    )}
                  >
                    {"If you can dream it, you can build it."}
                  </div>
                </ProductCard>
                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__puCjj
                  )}
                  img={{
                    src: "/plasmic/copy_of_t_22/images/shoe19.png",
                    fullWidth: 864,
                    fullHeight: 1080,
                    aspectRatio: undefined
                  }}
                  tags={
                    <Button
                      colors={"lightGray"}
                      size={"small"}
                      submitsForm={true}
                    >
                      {"New"}
                    </Button>
                  }
                />
              </Stack__>
            </div>
          </section>
          <section className={classNames(projectcss.all, sty.section___51Wu2)}>
            <Stack__
              as={"div"}
              data-plasmic-name={"container6"}
              data-plasmic-override={overrides.container6}
              hasGap={true}
              className={classNames(projectcss.all, sty.container6)}
            >
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__p4Hqk)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__e5GhS
                  )}
                >
                  {"Categories"}
                </div>
                <Button
                  className={classNames("__wab_instance", sty.button__mdzNr)}
                  states={"active"}
                  submitsForm={true}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___3Dzo5
                    )}
                  >
                    {"All"}
                  </div>
                </Button>
                <Button
                  className={classNames("__wab_instance", sty.button__ngYk9)}
                  submitsForm={true}
                >
                  {"New"}
                </Button>
                <Button
                  className={classNames("__wab_instance", sty.button__xzYl1)}
                  submitsForm={true}
                >
                  {"Womens"}
                </Button>
                <Button
                  className={classNames("__wab_instance", sty.button___66299)}
                  submitsForm={true}
                >
                  {"Mens"}
                </Button>
                <Button
                  className={classNames("__wab_instance", sty.button__rtByM)}
                  submitsForm={true}
                >
                  {"Kids"}
                </Button>
                <Button
                  className={classNames("__wab_instance", sty.button__vyxeA)}
                  submitsForm={true}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__hPuuX
                    )}
                  >
                    {"On sale"}
                  </div>
                </Button>
              </Stack__>
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox___5Yj7)}
              >
                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__h3PL
                  )}
                  img={{
                    src: "/plasmic/copy_of_t_22/images/shoe8.png",
                    fullWidth: 864,
                    fullHeight: 1080,
                    aspectRatio: undefined
                  }}
                  small={true}
                  tags={
                    <Button
                      colors={"lightGray"}
                      size={"small"}
                      submitsForm={true}
                    >
                      {"New"}
                    </Button>
                  }
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__ajNtL
                    )}
                  >
                    {"Nike Air Zoom Pegasus 38 Limited Edition"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__kF5R
                    )}
                  >
                    {"Women's Running Shoe"}
                  </div>
                </ProductCard>
                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__jPz0O
                  )}
                  img={{
                    src: "/plasmic/copy_of_t_22/images/shoe7.png",
                    fullWidth: 840,
                    fullHeight: 840,
                    aspectRatio: undefined
                  }}
                  small={true}
                  tags={
                    <Button
                      colors={"lightGray"}
                      size={"small"}
                      submitsForm={true}
                    >
                      {"New"}
                    </Button>
                  }
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__qxh00
                    )}
                  >
                    {"NMD_R1 SHOES"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__fDsin
                    )}
                  >
                    {"Continue the NMD legacy in these adidas NMD_R1 Shoes."}
                  </div>
                </ProductCard>
                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__drhQ
                  )}
                  img={{
                    src: "/plasmic/copy_of_t_22/images/shoe6.png",
                    fullWidth: 320,
                    fullHeight: 320,
                    aspectRatio: undefined
                  }}
                  small={true}
                  tags={
                    <Button
                      colors={"lightGray"}
                      size={"small"}
                      submitsForm={true}
                    >
                      {"New"}
                    </Button>
                  }
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___2I0V
                    )}
                  >
                    {"Question Low Men's Basketball Shoes"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__r7HFb
                    )}
                  >
                    {"Lace up fierce baller style."}
                  </div>
                </ProductCard>
                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__cxdW
                  )}
                  img={{
                    src: "/plasmic/copy_of_t_22/images/shoe5.png",
                    fullWidth: 2000,
                    fullHeight: 2000,
                    aspectRatio: undefined
                  }}
                  small={true}
                  tags={
                    <Button
                      colors={"lightGray"}
                      size={"small"}
                      submitsForm={true}
                    >
                      {"New"}
                    </Button>
                  }
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___2Gv3N
                    )}
                  >
                    {"Cali Women's Sneakers"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__hPgM2
                    )}
                  >
                    {"A sport style turned street classic."}
                  </div>
                </ProductCard>
                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__mlz6X
                  )}
                  img={{
                    src: "/plasmic/copy_of_t_22/images/shoe4.png",
                    fullWidth: 1024,
                    fullHeight: 768,
                    aspectRatio: undefined
                  }}
                  small={true}
                  tags={
                    <Button
                      colors={"lightGray"}
                      size={"small"}
                      submitsForm={true}
                    >
                      {"New"}
                    </Button>
                  }
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__pnvqC
                    )}
                  >
                    {"MAGIC SPEED"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__ztm4
                    )}
                  >
                    {"mMade for racing or regular training runs."}
                  </div>
                </ProductCard>
                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__bdb22
                  )}
                  img={{
                    src: "/plasmic/copy_of_t_22/images/shoe3.png",
                    fullWidth: 964,
                    fullHeight: 898,
                    aspectRatio: undefined
                  }}
                  small={true}
                  tags={
                    <Button
                      colors={"lightGray"}
                      size={"small"}
                      submitsForm={true}
                    >
                      {"New"}
                    </Button>
                  }
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__mcvGi
                    )}
                  >
                    {"Pride Chuck Taylor All Star"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___6EjGq
                    )}
                  >
                    {"If you can dream it, you can build it."}
                  </div>
                </ProductCard>
                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__dqp74
                  )}
                  img={{
                    src: "/plasmic/copy_of_t_22/images/shoe2.png",
                    fullWidth: 864,
                    fullHeight: 1080,
                    aspectRatio: undefined
                  }}
                  small={true}
                  tags={
                    <Button
                      colors={"lightGray"}
                      size={"small"}
                      submitsForm={true}
                    >
                      {"New"}
                    </Button>
                  }
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__qZtFf
                    )}
                  >
                    {"Nike Air Zoom Pegasus 38"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___0UqY9
                    )}
                  >
                    {"Your workhorse with wings returns."}
                  </div>
                </ProductCard>
                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__cejDk
                  )}
                  img={{
                    src: "/plasmic/copy_of_t_22/images/shoe9.png",
                    fullWidth: 1024,
                    fullHeight: 768,
                    aspectRatio: undefined
                  }}
                  small={true}
                  tags={
                    <Button
                      colors={"lightGray"}
                      size={"small"}
                      submitsForm={true}
                    >
                      {"New"}
                    </Button>
                  }
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___3X74W
                    )}
                  >
                    {"GEL-Nimbus 22 Retro Tokyo"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__t7TuP
                    )}
                  >
                    {"Enjoy comfort with each stride."}
                  </div>
                </ProductCard>
                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__lR1Y
                  )}
                  img={{
                    src: "/plasmic/copy_of_t_22/images/shoe10.png",
                    fullWidth: 964,
                    fullHeight: 898,
                    aspectRatio: undefined
                  }}
                  small={true}
                  tags={
                    <Button
                      colors={"lightGray"}
                      size={"small"}
                      submitsForm={true}
                    >
                      {"New"}
                    </Button>
                  }
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__qKvXk
                    )}
                  >
                    {"A Bug's World Chuck Taylor All Star"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__idx5Y
                    )}
                  >
                    {"Allover glow-in-the-dark bug prints."}
                  </div>
                </ProductCard>
                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__fz4P4
                  )}
                  img={{
                    src: "/plasmic/copy_of_t_22/images/shoe11.png",
                    fullWidth: 766,
                    fullHeight: 766,
                    aspectRatio: undefined
                  }}
                  small={true}
                  tags={
                    <Button
                      colors={"lightGray"}
                      size={"small"}
                      submitsForm={true}
                    >
                      {"New"}
                    </Button>
                  }
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__cEpCx
                    )}
                  >
                    {"NMD_R1 SHOES"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__b4Qyv
                    )}
                  >
                    {
                      "Effortlessly step up your look than a pop of animal print."
                    }
                  </div>
                </ProductCard>
                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__vuJkq
                  )}
                  img={{
                    src: "/plasmic/copy_of_t_22/images/shoe12.png",
                    fullWidth: 2000,
                    fullHeight: 2000,
                    aspectRatio: undefined
                  }}
                  small={true}
                  tags={
                    <Button
                      colors={"lightGray"}
                      size={"small"}
                      submitsForm={true}
                    >
                      {"New"}
                    </Button>
                  }
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__dsPVf
                    )}
                  >
                    {"Suede Teams Little Kids' Shoes"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__l10G
                    )}
                  >
                    {"Worn by the icons of every generation."}
                  </div>
                </ProductCard>
                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__ygCWa
                  )}
                  img={{
                    src: "/plasmic/copy_of_t_22/images/shoe13.png",
                    fullWidth: 840,
                    fullHeight: 840,
                    aspectRatio: undefined
                  }}
                  small={true}
                  tags={
                    <Button
                      colors={"lightGray"}
                      size={"small"}
                      submitsForm={true}
                    >
                      {"New"}
                    </Button>
                  }
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__i7Ik
                    )}
                  >
                    {"SUPERSTAR 360 PRIMEBLUE SANDALS"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__va7W7
                    )}
                  >
                    {"Your workhorse with wings returns."}
                  </div>
                </ProductCard>
              </Stack__>
            </Stack__>
          </section>
          <section
            className={classNames(projectcss.all, sty.section__gHIo1)}
            id={"goals"}
          >
            <Stack__
              as={"div"}
              data-plasmic-name={"container434"}
              data-plasmic-override={overrides.container434}
              hasGap={true}
              className={classNames(projectcss.all, sty.container434)}
            >
              <Value
                center={true}
                children2={
                  <Button
                    className={classNames("__wab_instance", sty.button__aVHwf)}
                    colors={"black"}
                    endIcon={
                      <RightArrowIcon
                        className={classNames(projectcss.all, sty.svg__ngF2G)}
                        role={"img"}
                      />
                    }
                    rounded={true}
                    showEndIcon={true}
                    submitsForm={true}
                  >
                    {"Read our letter"}
                  </Button>
                }
                className={classNames("__wab_instance", sty.value__mUaUc)}
                icon={
                  <SpeakerphoneIcon
                    className={classNames(projectcss.all, sty.svg__u4Ow)}
                    role={"img"}
                  />
                }
                topBottom={true}
                withButton={true}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__y4P89
                  )}
                >
                  {"Our goals"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__l2U6K
                  )}
                >
                  {"We\u2019re learning how to become a new kind of company."}
                </div>
              </Value>
            </Stack__>
          </section>
          <section className={classNames(projectcss.all, sty.section__xntsf)}>
            <Stack__
              as={"div"}
              data-plasmic-name={"container433"}
              data-plasmic-override={overrides.container433}
              hasGap={true}
              className={classNames(projectcss.all, sty.container433)}
            >
              <div className={classNames(projectcss.all, sty.column__z74Lc)}>
                <Value
                  children2={
                    <Button
                      className={classNames(
                        "__wab_instance",
                        sty.button__dwoFm
                      )}
                      colors={"black"}
                      endIcon={
                        <RightArrowIcon
                          className={classNames(projectcss.all, sty.svg__av11P)}
                          role={"img"}
                        />
                      }
                      rounded={true}
                      size={"large"}
                      submitsForm={true}
                    >
                      {"Read our letter"}
                    </Button>
                  }
                  className={classNames("__wab_instance", sty.value__nxusq)}
                  icon={
                    <MedalIcon
                      className={classNames(projectcss.all, sty.svg__tMzj3)}
                      role={"img"}
                    />
                  }
                  topBottom={true}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__stdjT
                    )}
                  >
                    {"We guarantee everything we sell."}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__fnkgw
                    )}
                  >
                    {
                      "Ad fringilla ut nisi in hendrerit malesuada nascetur a in ridiculus."
                    }
                  </div>
                  <Button
                    className={classNames("__wab_instance", sty.button__mvH4A)}
                    colors={"link"}
                    submitsForm={true}
                  >
                    {"View guarantee"}
                  </Button>
                </Value>
              </div>
              <div className={classNames(projectcss.all, sty.column__ew7YW)}>
                <Value
                  children2={
                    <Button
                      className={classNames(
                        "__wab_instance",
                        sty.button__mzLf3
                      )}
                      colors={"black"}
                      endIcon={
                        <RightArrowIcon
                          className={classNames(projectcss.all, sty.svg__sle17)}
                          role={"img"}
                        />
                      }
                      rounded={true}
                      size={"large"}
                      submitsForm={true}
                    >
                      {"Read our letter"}
                    </Button>
                  }
                  className={classNames("__wab_instance", sty.value___93ZXu)}
                  icon={
                    <LeafIcon
                      className={classNames(projectcss.all, sty.svg___26R5C)}
                      role={"img"}
                    />
                  }
                  topBottom={true}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__xXuGg
                    )}
                  >
                    {"Know how your shoes are made."}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__rR4Yr
                    )}
                  >
                    {
                      "Parturient blandit viverra blandit sem suspendisse himenaeos."
                    }
                  </div>
                  <Button
                    className={classNames("__wab_instance", sty.button__aFoek)}
                    colors={"link"}
                    submitsForm={true}
                  />
                </Value>
              </div>
              <div className={classNames(projectcss.all, sty.column__oa7E5)}>
                <Value
                  children2={
                    <Button
                      className={classNames(
                        "__wab_instance",
                        sty.button__ixzBf
                      )}
                      colors={"black"}
                      endIcon={
                        <RightArrowIcon
                          className={classNames(
                            projectcss.all,
                            sty.svg___1Scpc
                          )}
                          role={"img"}
                        />
                      }
                      rounded={true}
                      size={"large"}
                      submitsForm={true}
                    >
                      {"Read our letter"}
                    </Button>
                  }
                  className={classNames("__wab_instance", sty.value__wxgZc)}
                  icon={
                    <ShoeIcon
                      className={classNames(projectcss.all, sty.svg__bzyrc)}
                      role={"img"}
                    />
                  }
                  topBottom={true}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__bVypH
                    )}
                  >
                    {"Keep your shoes in play."}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__tvb
                    )}
                  >
                    {
                      "Adipiscing ornare dui tellus nam nibh cum a torquent maecenas."
                    }
                  </div>
                  <Button
                    className={classNames("__wab_instance", sty.button___3ZU7G)}
                    colors={"link"}
                    submitsForm={true}
                  />
                </Value>
              </div>
              <div className={classNames(projectcss.all, sty.column__qIvJq)}>
                <Value
                  children2={
                    <Button
                      className={classNames(
                        "__wab_instance",
                        sty.button__dlWk2
                      )}
                      colors={"black"}
                      endIcon={
                        <RightArrowIcon
                          className={classNames(projectcss.all, sty.svg__jxVwG)}
                          role={"img"}
                        />
                      }
                      rounded={true}
                      size={"large"}
                      submitsForm={true}
                    >
                      {"Read our letter"}
                    </Button>
                  }
                  className={classNames("__wab_instance", sty.value__hkuwA)}
                  icon={
                    <PeaceIcon
                      className={classNames(projectcss.all, sty.svg__t1JlY)}
                      role={"img"}
                    />
                  }
                  topBottom={true}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__gkfHg
                    )}
                  >
                    {"We give back for every sale."}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__plX1
                    )}
                  >
                    {
                      "Parturient vestibulum ut a dui parturient habitant netus integer ipsum."
                    }
                  </div>
                  <Button
                    className={classNames("__wab_instance", sty.button__gEsMz)}
                    colors={"link"}
                    submitsForm={true}
                  />
                </Value>
              </div>
            </Stack__>
          </section>
          <Footer
            data-plasmic-name={"footer"}
            data-plasmic-override={overrides.footer}
            className={classNames("__wab_instance", sty.footer)}
          />
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "navBar",
    "container3",
    "h1",
    "container4",
    "container",
    "emojiValueProps",
    "columns",
    "container42",
    "container5",
    "container6",
    "container434",
    "container433",
    "footer"
  ],
  navBar: ["navBar"],
  container3: ["container3", "h1"],
  h1: ["h1"],
  container4: ["container4"],
  container: ["container"],
  emojiValueProps: ["emojiValueProps", "columns"],
  columns: ["columns"],
  container42: ["container42"],
  container5: ["container5"],
  container6: ["container6"],
  container434: ["container434"],
  container433: ["container433"],
  footer: ["footer"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  navBar: typeof NavBar;
  container3: "div";
  h1: "h1";
  container4: "div";
  container: "div";
  emojiValueProps: typeof EmojiValueProps;
  columns: "div";
  container42: "div";
  container5: "div";
  container6: "div";
  container434: "div";
  container433: "div";
  footer: typeof Footer;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicHomepage__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicHomepage__VariantsArgs;
    args?: PlasmicHomepage__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicHomepage__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicHomepage__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicHomepage__ArgProps,
          internalVariantPropNames: PlasmicHomepage__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicHomepage__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicHomepage";
  } else {
    func.displayName = `PlasmicHomepage.${nodeName}`;
  }
  return func;
}

export const PlasmicHomepage = Object.assign(
  // Top-level PlasmicHomepage renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    navBar: makeNodeComponent("navBar"),
    container3: makeNodeComponent("container3"),
    h1: makeNodeComponent("h1"),
    container4: makeNodeComponent("container4"),
    container: makeNodeComponent("container"),
    emojiValueProps: makeNodeComponent("emojiValueProps"),
    columns: makeNodeComponent("columns"),
    container42: makeNodeComponent("container42"),
    container5: makeNodeComponent("container5"),
    container6: makeNodeComponent("container6"),
    container434: makeNodeComponent("container434"),
    container433: makeNodeComponent("container433"),
    footer: makeNodeComponent("footer"),

    // Metadata about props expected for PlasmicHomepage
    internalVariantProps: PlasmicHomepage__VariantProps,
    internalArgProps: PlasmicHomepage__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "ShoeShop",
      description:
        "Ad ullamcorper eros nibh pharetra vulputate imperdiet consectetur vestibulum at ac posuere volutpat maecenas gravida dictum suscipit habitasse class scelerisque fermentum blandit mi a.",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicHomepage;
/* prettier-ignore-end */
